# Generated by Django 2.0.10 on 2019-02-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodel',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
