# Generated by Django 2.0.10 on 2019-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_personaleducationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaleducationdetails',
            name='board_10th',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personaleducationdetails',
            name='board_12th',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personaleducationdetails',
            name='university',
            field=models.CharField(default='', max_length=50),
        ),
    ]
