# Generated by Django 2.0.10 on 2019-02-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190214_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailsmodel',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='personaldetailsmodel',
            name='current_country',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
