# Generated by Django 2.0.10 on 2019-02-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190215_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaleducationdetails',
            old_name='user_educational_details',
            new_name='user',
        ),
    ]
