# Generated by Django 2.0.10 on 2019-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190215_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaleducationdetails',
            name='year_of_graduation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaleducationdetails',
            name='year_passing_10th',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personaleducationdetails',
            name='year_passing_12th',
            field=models.IntegerField(null=True),
        ),
    ]
