# Generated by Django 2.0.10 on 2019-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190215_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaleducationdetails',
            name='course',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='personaleducationdetails',
            name='university',
            field=models.CharField(default='', max_length=500),
        ),
    ]
