# Generated by Django 2.0.10 on 2019-02-15 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_auto_20190215_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_course', models.TextField(default='', null=True)),
                ('duration', models.IntegerField(default=3, null=True)),
                ('university', models.CharField(default='', max_length=100)),
                ('course_completion_year', models.IntegerField(null=True)),
                ('subject', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
