# Generated by Django 2.0.10 on 2019-02-15 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_additionaleducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodel',
            name='current_city',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.City'),
        ),
        migrations.AddField(
            model_name='personaldetailsmodel',
            name='current_country',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Country'),
        ),
    ]
