# Generated by Django 2.0.10 on 2019-02-16 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0013_auto_20190215_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceAndProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.DateField(null=True)),
                ('name_of_organization', models.CharField(default='', max_length=500)),
                ('type_of_industry', models.CharField(default='', max_length=500)),
                ('dates_from', models.DateField(null=True)),
                ('dates_to', models.DateField(null=True)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('project_title', models.CharField(default='', max_length=500)),
                ('project_description', models.TextField(default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
