# Generated by Django 2.0.10 on 2019-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_experienceandprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaleducation',
            name='aggregate_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personaleducationdetails',
            name='cgpa_in_10th',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personaleducationdetails',
            name='cgpa_in_12th',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='personaleducationdetails',
            name='graduation_in_cgpa',
            field=models.FloatField(null=True),
        ),
    ]
