# Generated by Django 2.0.10 on 2019-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190216_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetailsmodel',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='personaldetailsmodel',
            name='current_country',
        ),
        migrations.AlterField(
            model_name='experienceandprojects',
            name='experience',
            field=models.FloatField(null=True),
        ),
    ]
