# Generated by Django 2.0.10 on 2019-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_skillsandtechnology'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodel',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personaldetailsmodel',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
