# Generated by Django 2.0.10 on 2019-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20190221_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
