# Generated by Django 2.0.10 on 2019-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_personaldetailsmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetailsmodel',
            name='Zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
