# Generated by Django 2.0.10 on 2019-02-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_personaldetailsmodel_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docfile',
            new_name='docFile',
        ),
    ]
