# Generated by Django 2.0.10 on 2019-02-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20190226_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaleducationdetails',
            old_name='graduation_in_cgpa',
            new_name='cgpa',
        ),
        migrations.RenameField(
            model_name='personaleducationdetails',
            old_name='subject_in_graduation',
            new_name='subject',
        ),
    ]
