# Generated by Django 2.0.10 on 2019-02-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20190228_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceandprojects',
            old_name='name_of_organization',
            new_name='Company',
        ),
    ]
