# Generated by Django 2.0.10 on 2019-03-11 10:17

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20190228_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docFile',
            field=models.FileField(upload_to=myapp.models.user_directory_path),
        ),
    ]
