# Generated by Django 2.0.10 on 2019-03-27 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0028_documentdatainjosnfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentDataInJosnFile',
            new_name='DocumentDataInJsonFile',
        ),
    ]
