# Generated by Django 2.0.10 on 2019-03-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20190327_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdatainjsonfile',
            name='documentData',
            field=models.TextField(default=''),
        ),
    ]
