# Generated by Django 2.0.10 on 2019-03-28 07:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20190328_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdatainjsonfile',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
