# Generated by Django 2.0.10 on 2019-03-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_auto_20190328_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdatainjsonfile',
            name='data',
        ),
    ]
